In [ ]:
Installation of numpy:


In [1]:
import numpy as np    #-----> alisa name numpy will be refered as np as a shortname.

In [ ]:
# Numpy will be dealing with n dimensional arrays:

In [ ]:
ndarrays:
    efficient to use and perform the code execution.
    reduces the time to generate the output

In [2]:
array_one=np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [3]:
numbers=[9,8,7,6,5]

In [4]:
array_two=np.array(numbers)
array_two

array([9, 8, 7, 6, 5])

In [ ]:
array built in methods (using matrices)

In [5]:
arrays_of_zeros=np.zeros((3,4))     #----> 3 rows 4 coloumns
arrays_of_zeros  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
arrays_of_ones=np.ones((2,3))
arrays_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Internally ndarrays use a float datatype

In [9]:
arrays_of_ones_int=np.ones((3,4),dtype=np.int16)    #----->converting into integers
arrays_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
Identity matrix:

In [12]:
arrays_eye=np.eye(3)     #----> np.eye() is the method we have to use for identity matrix
arrays_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
requirment is to print even numbers till 20 by using numpy and how to achive it:

In [13]:
arrays_of_even=np.arange(2,20,2)      # arange() is like range in python
arrays_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arrays_of_numbers=np.arange(1,11)
arrays_of_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])