In [ ]:
***Understanding Numpy:**
    
    Numpy deals with numerical computatuions 
    How to setup and use it

In [ ]:
Installation of numpy:

In [1]:
!pip install numpy

Unable to create process using 'C:\Users\Ruvan Paripelly\anaconda31\python.exe "C:\Users\Ruvan Paripelly\anaconda31\Scripts\pip-script.py" install numpy'


In [2]:
import numpy as np    #------------->importing numpy module

In [ ]:
Understanding ndarrays:Datatype "ndarray"
    
NUmpy will be acting as base library to all the libraries in python.

In [3]:
array_one=np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [4]:
type(array_one)    #-----declaring the type

numpy.ndarray

In [5]:
numbers=[9,8,7,6,5]    #---->1D i,e one dimensional array

In [6]:
array_two=np.array(numbers)
array_two

array([9, 8, 7, 6, 5])

In [ ]:
example for two dimensional arrays:

In [7]:
array_of_zeros=np.zeros((3,4))    #----->2D i,e two dimensional array

array_of_zeros                    #----->gives output as float values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
**ndarrays====means===> N dimensional arrays**

In [ ]:
To know the dimensions in the array we do:
    arrayname.shape
example take above as example

In [8]:
array_of_zeros.shape   #------> the above example as 3 rows and 4 coloumns

(3, 4)

In [9]:
array_of_ones=np.ones((2,5))   #-----> 2 rows and 5 coloumns
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
if we want the output in integer form then:

In [10]:
array_of_ones_int=np.ones((3,4),dtype=np.int16)     #------> dtype converts data into integer types and int16==16 bit data

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)