In [ ]:
Continuation of Numpy:

In [1]:
import numpy as np

In [ ]:
req: If want squares from 1 tp 10 then

In [2]:
a=np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [3]:
a[4]

16

In [ ]:
req:accessing by using the -ve indexing

In [4]:
a[-2]

81

In [ ]:
req: Slicing of arrays:

In [5]:
a[1:5]     #------->start and stop values

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
req: Reversing of arrays

In [6]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [ ]:
req: How to iterate over arrays:

In [7]:
a      #--------------> squares of numbers from 1 to 10

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
for i in a:
    print(i**(1/2))     #------> output we get is the actual numbers from 1 to 10
                                # i.e By square root of the squares of numbers

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
